In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Load dataset
dataset=pd.read_csv("customer_shopping.csv")

In [46]:
# dataset information
first_five=dataset.head()
description=dataset.describe()
information=dataset.info
last_five=dataset.tail()
column=dataset.columns
random_row=dataset.sample()
distinct=dataset.nunique()
dataset["Age"].describe()
dataset["Location"].value_counts()
dataset["Review_Rating"].describe()
dataset["Payment_Method"].value_counts()

Payment_Method
Debit Card        119
Bank Transfer     108
Cash               98
Digital Wallet     89
Credit Card        89
Name: count, dtype: int64

In [66]:
# Handling Missing values
missing=dataset.isnull().sum()
dataset["Age"]=dataset["Age"].fillna(41)
dataset["Age"].isnull().sum()
dataset["Location"]=dataset["Location"].fillna("Unknown")
dataset["Location"].isnull().sum()
dataset["Review_Rating"]=dataset["Review_Rating"].fillna(5)
dataset["Review_Rating"].isnull().sum()
dataset["Payment_Method"]=dataset["Payment_Method"].fillna("Debit card")
dataset["Payment_Method"].isnull().sum()
missing2=dataset.isnull().sum()
dataset["Location"].unique()

<ArrowStringArray>
['Multan', 'Lahore', 'Islamabad', 'Faisalabad', 'Karachi', 'Peshawar']
Length: 6, dtype: str

In [74]:
dataset.duplicated()
dataset.drop_duplicates()
dataset[dataset.duplicated()]

,Customer_ID,Age,Gender,Location,Product_Category,Item_Purchased,Purchase_Amount,Discount_Percent,Review_Rating,Previous_Purchases,Subscription_Status,Payment_Method,Shipping_Type,Purchase_Frequency
500,10034,44.0,Male,Karachi,Beauty,Face Cream,3645.0,30,5.0,15,No,Credit Card,Standard,Monthly
501,10145,65.0,Male,Islamabad,Home,Bedsheet,5009.0,20,3.9,9,Yes,Debit Card,Standard,Fortnightly
502,10288,45.0,Male,Lahore,Electronics,Headphones,4693.0,15,3.6,1,No,Credit Card,Express,Monthly

In [20]:
dataset.head()

,Customer_ID,Age,Gender,Location,Product_Category,Item_Purchased,Purchase_Amount,Discount_Percent,Review_Rating,Previous_Purchases,Subscription_Status,Payment_Method,Shipping_Type,Purchase_Frequency
0,10001,22.0,Female,Multan,Clothing,Sneakers,5072.0,20,4.6,23,No,Digital Wallet,Same Day,Monthly
1,10002,55.0,Female,Lahore,Electronics,Keyboard,6755.0,0,4.2,23,No,Credit Card,Standard,Monthly
2,10003,49.0,Male,Multan,Clothing,Sneakers,4139.0,10,3.9,7,Yes,Digital Wallet,Express,Weekly
3,10004,39.0,Male,Lahore,Electronics,Smartwatch,3222.0,20,4.1,14,No,Cash,Express,Monthly
4,10005,38.0,Male,Lahore,Home,Cookware,500.0,30,3.1,4,No,Debit Card,Standard,Weekly

Customer_ID            0
Age                    0
Gender                 0
Location               0
Product_Category       0
Item_Purchased         0
Purchase_Amount        0
Discount_Percent       0
Review_Rating          0
Previous_Purchases     0
Subscription_Status    0
Payment_Method         0
Shipping_Type          0
Purchase_Frequency     0
dtype: int64